//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.8.3928.0。
// 
namespace GGZY.DataService.ConvergenceService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <summary>
    /// 4.1.1 身份验证，获取guid   编号I000101
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticationSoap", Namespace="http://tempuri.org/")]
    public partial class Authentication : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginByAccountOperationCompleted;
        
        /// <remarks/>
        public Authentication() {
            this.Url = "http://220.160.52.50:801/ConvergenceSerivce/Authentication.asmx";
        }
        
        /// <remarks/>
        public event loginByAccountCompletedEventHandler loginByAccountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/loginByAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string loginByAccount(string userid, string password) {
            object[] results = this.Invoke("loginByAccount", new object[] {
                        userid,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginloginByAccount(string userid, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("loginByAccount", new object[] {
                        userid,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndloginByAccount(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginByAccountAsync(string userid, string password) {
            this.loginByAccountAsync(userid, password, null);
        }
        
        /// <remarks/>
        public void loginByAccountAsync(string userid, string password, object userState) {
            if ((this.loginByAccountOperationCompleted == null)) {
                this.loginByAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginByAccountOperationCompleted);
            }
            this.InvokeAsync("loginByAccount", new object[] {
                        userid,
                        password}, this.loginByAccountOperationCompleted, userState);
        }
        
        private void OnloginByAccountOperationCompleted(object arg) {
            if ((this.loginByAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginByAccountCompleted(this, new loginByAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void loginByAccountCompletedEventHandler(object sender, loginByAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginByAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginByAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
