//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.8.3928.0。
// 
namespace PullData.ConvergenceService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EnterpInfoSoap", Namespace="http://tempuri.org/")]
    public partial class EnterpInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback queryByEnterpOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryByUSCCOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryAllByEnterpOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryByCnnameOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsZzjgdmExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsZzjgdmAndNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsNameExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNameByZzjgdmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetZzjgdmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNameByFuzzySearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNameByNotRemoveWordFuzzySearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllByNameFuzzySearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllByNotRemoveWordFuzzySearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllByZzjgdmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoByTYSHXYDMOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryBytyshxydmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNameZzjgdmByFuzzySearchOperationCompleted;
        
        /// <remarks/>
        public EnterpInfo() {
            this.Url = "http://220.160.52.50:801/ConvergenceSerivce/EnterpInfo.asmx";
        }
        
        /// <remarks/>
        public event queryByEnterpCompletedEventHandler queryByEnterpCompleted;
        
        /// <remarks/>
        public event queryByUSCCCompletedEventHandler queryByUSCCCompleted;
        
        /// <remarks/>
        public event queryAllByEnterpCompletedEventHandler queryAllByEnterpCompleted;
        
        /// <remarks/>
        public event queryByIDCompletedEventHandler queryByIDCompleted;
        
        /// <remarks/>
        public event queryByCnnameCompletedEventHandler queryByCnnameCompleted;
        
        /// <remarks/>
        public event IsZzjgdmExistCompletedEventHandler IsZzjgdmExistCompleted;
        
        /// <remarks/>
        public event IsZzjgdmAndNameCompletedEventHandler IsZzjgdmAndNameCompleted;
        
        /// <remarks/>
        public event IsNameExistCompletedEventHandler IsNameExistCompleted;
        
        /// <remarks/>
        public event GetNameByZzjgdmCompletedEventHandler GetNameByZzjgdmCompleted;
        
        /// <remarks/>
        public event GetZzjgdmCompletedEventHandler GetZzjgdmCompleted;
        
        /// <remarks/>
        public event GetNameByFuzzySearchCompletedEventHandler GetNameByFuzzySearchCompleted;
        
        /// <remarks/>
        public event GetNameByNotRemoveWordFuzzySearchCompletedEventHandler GetNameByNotRemoveWordFuzzySearchCompleted;
        
        /// <remarks/>
        public event GetAllByNameFuzzySearchCompletedEventHandler GetAllByNameFuzzySearchCompleted;
        
        /// <remarks/>
        public event GetAllByNotRemoveWordFuzzySearchCompletedEventHandler GetAllByNotRemoveWordFuzzySearchCompleted;
        
        /// <remarks/>
        public event GetAllByZzjgdmCompletedEventHandler GetAllByZzjgdmCompleted;
        
        /// <remarks/>
        public event GetAllByNameCompletedEventHandler GetAllByNameCompleted;
        
        /// <remarks/>
        public event GetInfoByNameCompletedEventHandler GetInfoByNameCompleted;
        
        /// <remarks/>
        public event GetInfoByTYSHXYDMCompletedEventHandler GetInfoByTYSHXYDMCompleted;
        
        /// <remarks/>
        public event queryBytyshxydmCompletedEventHandler queryBytyshxydmCompleted;
        
        /// <remarks/>
        public event GetNameZzjgdmByFuzzySearchCompletedEventHandler GetNameZzjgdmByFuzzySearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryByEnterp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryByEnterp(string guid, string enterp) {
            object[] results = this.Invoke("queryByEnterp", new object[] {
                        guid,
                        enterp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryByEnterp(string guid, string enterp, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryByEnterp", new object[] {
                        guid,
                        enterp}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryByEnterp(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryByEnterpAsync(string guid, string enterp) {
            this.queryByEnterpAsync(guid, enterp, null);
        }
        
        /// <remarks/>
        public void queryByEnterpAsync(string guid, string enterp, object userState) {
            if ((this.queryByEnterpOperationCompleted == null)) {
                this.queryByEnterpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryByEnterpOperationCompleted);
            }
            this.InvokeAsync("queryByEnterp", new object[] {
                        guid,
                        enterp}, this.queryByEnterpOperationCompleted, userState);
        }
        
        private void OnqueryByEnterpOperationCompleted(object arg) {
            if ((this.queryByEnterpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryByEnterpCompleted(this, new queryByEnterpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryByUSCC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryByUSCC(string guid, string USCC) {
            object[] results = this.Invoke("queryByUSCC", new object[] {
                        guid,
                        USCC});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryByUSCC(string guid, string USCC, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryByUSCC", new object[] {
                        guid,
                        USCC}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryByUSCC(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryByUSCCAsync(string guid, string USCC) {
            this.queryByUSCCAsync(guid, USCC, null);
        }
        
        /// <remarks/>
        public void queryByUSCCAsync(string guid, string USCC, object userState) {
            if ((this.queryByUSCCOperationCompleted == null)) {
                this.queryByUSCCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryByUSCCOperationCompleted);
            }
            this.InvokeAsync("queryByUSCC", new object[] {
                        guid,
                        USCC}, this.queryByUSCCOperationCompleted, userState);
        }
        
        private void OnqueryByUSCCOperationCompleted(object arg) {
            if ((this.queryByUSCCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryByUSCCCompleted(this, new queryByUSCCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryAllByEnterp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryAllByEnterp(string guid, string enterp) {
            object[] results = this.Invoke("queryAllByEnterp", new object[] {
                        guid,
                        enterp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryAllByEnterp(string guid, string enterp, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryAllByEnterp", new object[] {
                        guid,
                        enterp}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryAllByEnterp(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryAllByEnterpAsync(string guid, string enterp) {
            this.queryAllByEnterpAsync(guid, enterp, null);
        }
        
        /// <remarks/>
        public void queryAllByEnterpAsync(string guid, string enterp, object userState) {
            if ((this.queryAllByEnterpOperationCompleted == null)) {
                this.queryAllByEnterpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryAllByEnterpOperationCompleted);
            }
            this.InvokeAsync("queryAllByEnterp", new object[] {
                        guid,
                        enterp}, this.queryAllByEnterpOperationCompleted, userState);
        }
        
        private void OnqueryAllByEnterpOperationCompleted(object arg) {
            if ((this.queryAllByEnterpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryAllByEnterpCompleted(this, new queryAllByEnterpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryByID(string guid, string id) {
            object[] results = this.Invoke("queryByID", new object[] {
                        guid,
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryByID(string guid, string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryByID", new object[] {
                        guid,
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryByIDAsync(string guid, string id) {
            this.queryByIDAsync(guid, id, null);
        }
        
        /// <remarks/>
        public void queryByIDAsync(string guid, string id, object userState) {
            if ((this.queryByIDOperationCompleted == null)) {
                this.queryByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryByIDOperationCompleted);
            }
            this.InvokeAsync("queryByID", new object[] {
                        guid,
                        id}, this.queryByIDOperationCompleted, userState);
        }
        
        private void OnqueryByIDOperationCompleted(object arg) {
            if ((this.queryByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryByIDCompleted(this, new queryByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryByCnname", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryByCnname(string guid, string cnname) {
            object[] results = this.Invoke("queryByCnname", new object[] {
                        guid,
                        cnname});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryByCnname(string guid, string cnname, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryByCnname", new object[] {
                        guid,
                        cnname}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryByCnname(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryByCnnameAsync(string guid, string cnname) {
            this.queryByCnnameAsync(guid, cnname, null);
        }
        
        /// <remarks/>
        public void queryByCnnameAsync(string guid, string cnname, object userState) {
            if ((this.queryByCnnameOperationCompleted == null)) {
                this.queryByCnnameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryByCnnameOperationCompleted);
            }
            this.InvokeAsync("queryByCnname", new object[] {
                        guid,
                        cnname}, this.queryByCnnameOperationCompleted, userState);
        }
        
        private void OnqueryByCnnameOperationCompleted(object arg) {
            if ((this.queryByCnnameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryByCnnameCompleted(this, new queryByCnnameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsZzjgdmExist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsZzjgdmExist(string guid, string zzjgdm) {
            object[] results = this.Invoke("IsZzjgdmExist", new object[] {
                        guid,
                        zzjgdm});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsZzjgdmExist(string guid, string zzjgdm, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsZzjgdmExist", new object[] {
                        guid,
                        zzjgdm}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsZzjgdmExist(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsZzjgdmExistAsync(string guid, string zzjgdm) {
            this.IsZzjgdmExistAsync(guid, zzjgdm, null);
        }
        
        /// <remarks/>
        public void IsZzjgdmExistAsync(string guid, string zzjgdm, object userState) {
            if ((this.IsZzjgdmExistOperationCompleted == null)) {
                this.IsZzjgdmExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsZzjgdmExistOperationCompleted);
            }
            this.InvokeAsync("IsZzjgdmExist", new object[] {
                        guid,
                        zzjgdm}, this.IsZzjgdmExistOperationCompleted, userState);
        }
        
        private void OnIsZzjgdmExistOperationCompleted(object arg) {
            if ((this.IsZzjgdmExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsZzjgdmExistCompleted(this, new IsZzjgdmExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsZzjgdmAndName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsZzjgdmAndName(string guid, string zzjgdm, string name) {
            object[] results = this.Invoke("IsZzjgdmAndName", new object[] {
                        guid,
                        zzjgdm,
                        name});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsZzjgdmAndName(string guid, string zzjgdm, string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsZzjgdmAndName", new object[] {
                        guid,
                        zzjgdm,
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsZzjgdmAndName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsZzjgdmAndNameAsync(string guid, string zzjgdm, string name) {
            this.IsZzjgdmAndNameAsync(guid, zzjgdm, name, null);
        }
        
        /// <remarks/>
        public void IsZzjgdmAndNameAsync(string guid, string zzjgdm, string name, object userState) {
            if ((this.IsZzjgdmAndNameOperationCompleted == null)) {
                this.IsZzjgdmAndNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsZzjgdmAndNameOperationCompleted);
            }
            this.InvokeAsync("IsZzjgdmAndName", new object[] {
                        guid,
                        zzjgdm,
                        name}, this.IsZzjgdmAndNameOperationCompleted, userState);
        }
        
        private void OnIsZzjgdmAndNameOperationCompleted(object arg) {
            if ((this.IsZzjgdmAndNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsZzjgdmAndNameCompleted(this, new IsZzjgdmAndNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsNameExist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsNameExist(string guid, string name) {
            object[] results = this.Invoke("IsNameExist", new object[] {
                        guid,
                        name});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsNameExist(string guid, string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsNameExist", new object[] {
                        guid,
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsNameExist(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsNameExistAsync(string guid, string name) {
            this.IsNameExistAsync(guid, name, null);
        }
        
        /// <remarks/>
        public void IsNameExistAsync(string guid, string name, object userState) {
            if ((this.IsNameExistOperationCompleted == null)) {
                this.IsNameExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsNameExistOperationCompleted);
            }
            this.InvokeAsync("IsNameExist", new object[] {
                        guid,
                        name}, this.IsNameExistOperationCompleted, userState);
        }
        
        private void OnIsNameExistOperationCompleted(object arg) {
            if ((this.IsNameExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsNameExistCompleted(this, new IsNameExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNameByZzjgdm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNameByZzjgdm(string guid, string zzjgdm) {
            object[] results = this.Invoke("GetNameByZzjgdm", new object[] {
                        guid,
                        zzjgdm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetNameByZzjgdm(string guid, string zzjgdm, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetNameByZzjgdm", new object[] {
                        guid,
                        zzjgdm}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetNameByZzjgdm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNameByZzjgdmAsync(string guid, string zzjgdm) {
            this.GetNameByZzjgdmAsync(guid, zzjgdm, null);
        }
        
        /// <remarks/>
        public void GetNameByZzjgdmAsync(string guid, string zzjgdm, object userState) {
            if ((this.GetNameByZzjgdmOperationCompleted == null)) {
                this.GetNameByZzjgdmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNameByZzjgdmOperationCompleted);
            }
            this.InvokeAsync("GetNameByZzjgdm", new object[] {
                        guid,
                        zzjgdm}, this.GetNameByZzjgdmOperationCompleted, userState);
        }
        
        private void OnGetNameByZzjgdmOperationCompleted(object arg) {
            if ((this.GetNameByZzjgdmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNameByZzjgdmCompleted(this, new GetNameByZzjgdmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetZzjgdm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetZzjgdm(string guid, string name) {
            object[] results = this.Invoke("GetZzjgdm", new object[] {
                        guid,
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetZzjgdm(string guid, string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetZzjgdm", new object[] {
                        guid,
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetZzjgdm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetZzjgdmAsync(string guid, string name) {
            this.GetZzjgdmAsync(guid, name, null);
        }
        
        /// <remarks/>
        public void GetZzjgdmAsync(string guid, string name, object userState) {
            if ((this.GetZzjgdmOperationCompleted == null)) {
                this.GetZzjgdmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetZzjgdmOperationCompleted);
            }
            this.InvokeAsync("GetZzjgdm", new object[] {
                        guid,
                        name}, this.GetZzjgdmOperationCompleted, userState);
        }
        
        private void OnGetZzjgdmOperationCompleted(object arg) {
            if ((this.GetZzjgdmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetZzjgdmCompleted(this, new GetZzjgdmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNameByFuzzySearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNameByFuzzySearch(string guid, string name) {
            object[] results = this.Invoke("GetNameByFuzzySearch", new object[] {
                        guid,
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetNameByFuzzySearch(string guid, string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetNameByFuzzySearch", new object[] {
                        guid,
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetNameByFuzzySearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNameByFuzzySearchAsync(string guid, string name) {
            this.GetNameByFuzzySearchAsync(guid, name, null);
        }
        
        /// <remarks/>
        public void GetNameByFuzzySearchAsync(string guid, string name, object userState) {
            if ((this.GetNameByFuzzySearchOperationCompleted == null)) {
                this.GetNameByFuzzySearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNameByFuzzySearchOperationCompleted);
            }
            this.InvokeAsync("GetNameByFuzzySearch", new object[] {
                        guid,
                        name}, this.GetNameByFuzzySearchOperationCompleted, userState);
        }
        
        private void OnGetNameByFuzzySearchOperationCompleted(object arg) {
            if ((this.GetNameByFuzzySearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNameByFuzzySearchCompleted(this, new GetNameByFuzzySearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNameByNotRemoveWordFuzzySearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNameByNotRemoveWordFuzzySearch(string guid, string name) {
            object[] results = this.Invoke("GetNameByNotRemoveWordFuzzySearch", new object[] {
                        guid,
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetNameByNotRemoveWordFuzzySearch(string guid, string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetNameByNotRemoveWordFuzzySearch", new object[] {
                        guid,
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetNameByNotRemoveWordFuzzySearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNameByNotRemoveWordFuzzySearchAsync(string guid, string name) {
            this.GetNameByNotRemoveWordFuzzySearchAsync(guid, name, null);
        }
        
        /// <remarks/>
        public void GetNameByNotRemoveWordFuzzySearchAsync(string guid, string name, object userState) {
            if ((this.GetNameByNotRemoveWordFuzzySearchOperationCompleted == null)) {
                this.GetNameByNotRemoveWordFuzzySearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNameByNotRemoveWordFuzzySearchOperationCompleted);
            }
            this.InvokeAsync("GetNameByNotRemoveWordFuzzySearch", new object[] {
                        guid,
                        name}, this.GetNameByNotRemoveWordFuzzySearchOperationCompleted, userState);
        }
        
        private void OnGetNameByNotRemoveWordFuzzySearchOperationCompleted(object arg) {
            if ((this.GetNameByNotRemoveWordFuzzySearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNameByNotRemoveWordFuzzySearchCompleted(this, new GetNameByNotRemoveWordFuzzySearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllByNameFuzzySearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAllByNameFuzzySearch(string guid, string name) {
            object[] results = this.Invoke("GetAllByNameFuzzySearch", new object[] {
                        guid,
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAllByNameFuzzySearch(string guid, string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAllByNameFuzzySearch", new object[] {
                        guid,
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAllByNameFuzzySearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllByNameFuzzySearchAsync(string guid, string name) {
            this.GetAllByNameFuzzySearchAsync(guid, name, null);
        }
        
        /// <remarks/>
        public void GetAllByNameFuzzySearchAsync(string guid, string name, object userState) {
            if ((this.GetAllByNameFuzzySearchOperationCompleted == null)) {
                this.GetAllByNameFuzzySearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllByNameFuzzySearchOperationCompleted);
            }
            this.InvokeAsync("GetAllByNameFuzzySearch", new object[] {
                        guid,
                        name}, this.GetAllByNameFuzzySearchOperationCompleted, userState);
        }
        
        private void OnGetAllByNameFuzzySearchOperationCompleted(object arg) {
            if ((this.GetAllByNameFuzzySearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllByNameFuzzySearchCompleted(this, new GetAllByNameFuzzySearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllByNotRemoveWordFuzzySearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAllByNotRemoveWordFuzzySearch(string guid, string name) {
            object[] results = this.Invoke("GetAllByNotRemoveWordFuzzySearch", new object[] {
                        guid,
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAllByNotRemoveWordFuzzySearch(string guid, string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAllByNotRemoveWordFuzzySearch", new object[] {
                        guid,
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAllByNotRemoveWordFuzzySearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllByNotRemoveWordFuzzySearchAsync(string guid, string name) {
            this.GetAllByNotRemoveWordFuzzySearchAsync(guid, name, null);
        }
        
        /// <remarks/>
        public void GetAllByNotRemoveWordFuzzySearchAsync(string guid, string name, object userState) {
            if ((this.GetAllByNotRemoveWordFuzzySearchOperationCompleted == null)) {
                this.GetAllByNotRemoveWordFuzzySearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllByNotRemoveWordFuzzySearchOperationCompleted);
            }
            this.InvokeAsync("GetAllByNotRemoveWordFuzzySearch", new object[] {
                        guid,
                        name}, this.GetAllByNotRemoveWordFuzzySearchOperationCompleted, userState);
        }
        
        private void OnGetAllByNotRemoveWordFuzzySearchOperationCompleted(object arg) {
            if ((this.GetAllByNotRemoveWordFuzzySearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllByNotRemoveWordFuzzySearchCompleted(this, new GetAllByNotRemoveWordFuzzySearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllByZzjgdm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAllByZzjgdm(string guid, string zzjgdm) {
            object[] results = this.Invoke("GetAllByZzjgdm", new object[] {
                        guid,
                        zzjgdm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAllByZzjgdm(string guid, string zzjgdm, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAllByZzjgdm", new object[] {
                        guid,
                        zzjgdm}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAllByZzjgdm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllByZzjgdmAsync(string guid, string zzjgdm) {
            this.GetAllByZzjgdmAsync(guid, zzjgdm, null);
        }
        
        /// <remarks/>
        public void GetAllByZzjgdmAsync(string guid, string zzjgdm, object userState) {
            if ((this.GetAllByZzjgdmOperationCompleted == null)) {
                this.GetAllByZzjgdmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllByZzjgdmOperationCompleted);
            }
            this.InvokeAsync("GetAllByZzjgdm", new object[] {
                        guid,
                        zzjgdm}, this.GetAllByZzjgdmOperationCompleted, userState);
        }
        
        private void OnGetAllByZzjgdmOperationCompleted(object arg) {
            if ((this.GetAllByZzjgdmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllByZzjgdmCompleted(this, new GetAllByZzjgdmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAllByName(string guid, string name) {
            object[] results = this.Invoke("GetAllByName", new object[] {
                        guid,
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAllByName(string guid, string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAllByName", new object[] {
                        guid,
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAllByName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllByNameAsync(string guid, string name) {
            this.GetAllByNameAsync(guid, name, null);
        }
        
        /// <remarks/>
        public void GetAllByNameAsync(string guid, string name, object userState) {
            if ((this.GetAllByNameOperationCompleted == null)) {
                this.GetAllByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllByNameOperationCompleted);
            }
            this.InvokeAsync("GetAllByName", new object[] {
                        guid,
                        name}, this.GetAllByNameOperationCompleted, userState);
        }
        
        private void OnGetAllByNameOperationCompleted(object arg) {
            if ((this.GetAllByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllByNameCompleted(this, new GetAllByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfoByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetInfoByName(string guid, string name) {
            object[] results = this.Invoke("GetInfoByName", new object[] {
                        guid,
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInfoByName(string guid, string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInfoByName", new object[] {
                        guid,
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetInfoByName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoByNameAsync(string guid, string name) {
            this.GetInfoByNameAsync(guid, name, null);
        }
        
        /// <remarks/>
        public void GetInfoByNameAsync(string guid, string name, object userState) {
            if ((this.GetInfoByNameOperationCompleted == null)) {
                this.GetInfoByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoByNameOperationCompleted);
            }
            this.InvokeAsync("GetInfoByName", new object[] {
                        guid,
                        name}, this.GetInfoByNameOperationCompleted, userState);
        }
        
        private void OnGetInfoByNameOperationCompleted(object arg) {
            if ((this.GetInfoByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoByNameCompleted(this, new GetInfoByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfoByTYSHXYDM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetInfoByTYSHXYDM(string guid, string tyshxydm) {
            object[] results = this.Invoke("GetInfoByTYSHXYDM", new object[] {
                        guid,
                        tyshxydm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInfoByTYSHXYDM(string guid, string tyshxydm, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInfoByTYSHXYDM", new object[] {
                        guid,
                        tyshxydm}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetInfoByTYSHXYDM(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoByTYSHXYDMAsync(string guid, string tyshxydm) {
            this.GetInfoByTYSHXYDMAsync(guid, tyshxydm, null);
        }
        
        /// <remarks/>
        public void GetInfoByTYSHXYDMAsync(string guid, string tyshxydm, object userState) {
            if ((this.GetInfoByTYSHXYDMOperationCompleted == null)) {
                this.GetInfoByTYSHXYDMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoByTYSHXYDMOperationCompleted);
            }
            this.InvokeAsync("GetInfoByTYSHXYDM", new object[] {
                        guid,
                        tyshxydm}, this.GetInfoByTYSHXYDMOperationCompleted, userState);
        }
        
        private void OnGetInfoByTYSHXYDMOperationCompleted(object arg) {
            if ((this.GetInfoByTYSHXYDMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoByTYSHXYDMCompleted(this, new GetInfoByTYSHXYDMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryBytyshxydm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryBytyshxydm(string guid, string requestid, string tyshxydm) {
            object[] results = this.Invoke("queryBytyshxydm", new object[] {
                        guid,
                        requestid,
                        tyshxydm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryBytyshxydm(string guid, string requestid, string tyshxydm, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryBytyshxydm", new object[] {
                        guid,
                        requestid,
                        tyshxydm}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryBytyshxydm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryBytyshxydmAsync(string guid, string requestid, string tyshxydm) {
            this.queryBytyshxydmAsync(guid, requestid, tyshxydm, null);
        }
        
        /// <remarks/>
        public void queryBytyshxydmAsync(string guid, string requestid, string tyshxydm, object userState) {
            if ((this.queryBytyshxydmOperationCompleted == null)) {
                this.queryBytyshxydmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryBytyshxydmOperationCompleted);
            }
            this.InvokeAsync("queryBytyshxydm", new object[] {
                        guid,
                        requestid,
                        tyshxydm}, this.queryBytyshxydmOperationCompleted, userState);
        }
        
        private void OnqueryBytyshxydmOperationCompleted(object arg) {
            if ((this.queryBytyshxydmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryBytyshxydmCompleted(this, new queryBytyshxydmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNameZzjgdmByFuzzySearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNameZzjgdmByFuzzySearch(string guid, string name) {
            object[] results = this.Invoke("GetNameZzjgdmByFuzzySearch", new object[] {
                        guid,
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetNameZzjgdmByFuzzySearch(string guid, string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetNameZzjgdmByFuzzySearch", new object[] {
                        guid,
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetNameZzjgdmByFuzzySearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNameZzjgdmByFuzzySearchAsync(string guid, string name) {
            this.GetNameZzjgdmByFuzzySearchAsync(guid, name, null);
        }
        
        /// <remarks/>
        public void GetNameZzjgdmByFuzzySearchAsync(string guid, string name, object userState) {
            if ((this.GetNameZzjgdmByFuzzySearchOperationCompleted == null)) {
                this.GetNameZzjgdmByFuzzySearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNameZzjgdmByFuzzySearchOperationCompleted);
            }
            this.InvokeAsync("GetNameZzjgdmByFuzzySearch", new object[] {
                        guid,
                        name}, this.GetNameZzjgdmByFuzzySearchOperationCompleted, userState);
        }
        
        private void OnGetNameZzjgdmByFuzzySearchOperationCompleted(object arg) {
            if ((this.GetNameZzjgdmByFuzzySearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNameZzjgdmByFuzzySearchCompleted(this, new GetNameZzjgdmByFuzzySearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void queryByEnterpCompletedEventHandler(object sender, queryByEnterpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryByEnterpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryByEnterpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void queryByUSCCCompletedEventHandler(object sender, queryByUSCCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryByUSCCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryByUSCCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void queryAllByEnterpCompletedEventHandler(object sender, queryAllByEnterpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryAllByEnterpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryAllByEnterpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void queryByIDCompletedEventHandler(object sender, queryByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void queryByCnnameCompletedEventHandler(object sender, queryByCnnameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryByCnnameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryByCnnameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void IsZzjgdmExistCompletedEventHandler(object sender, IsZzjgdmExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsZzjgdmExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsZzjgdmExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void IsZzjgdmAndNameCompletedEventHandler(object sender, IsZzjgdmAndNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsZzjgdmAndNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsZzjgdmAndNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void IsNameExistCompletedEventHandler(object sender, IsNameExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsNameExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsNameExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetNameByZzjgdmCompletedEventHandler(object sender, GetNameByZzjgdmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNameByZzjgdmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNameByZzjgdmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetZzjgdmCompletedEventHandler(object sender, GetZzjgdmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetZzjgdmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetZzjgdmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetNameByFuzzySearchCompletedEventHandler(object sender, GetNameByFuzzySearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNameByFuzzySearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNameByFuzzySearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetNameByNotRemoveWordFuzzySearchCompletedEventHandler(object sender, GetNameByNotRemoveWordFuzzySearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNameByNotRemoveWordFuzzySearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNameByNotRemoveWordFuzzySearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetAllByNameFuzzySearchCompletedEventHandler(object sender, GetAllByNameFuzzySearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllByNameFuzzySearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllByNameFuzzySearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetAllByNotRemoveWordFuzzySearchCompletedEventHandler(object sender, GetAllByNotRemoveWordFuzzySearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllByNotRemoveWordFuzzySearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllByNotRemoveWordFuzzySearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetAllByZzjgdmCompletedEventHandler(object sender, GetAllByZzjgdmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllByZzjgdmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllByZzjgdmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetAllByNameCompletedEventHandler(object sender, GetAllByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetInfoByNameCompletedEventHandler(object sender, GetInfoByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetInfoByTYSHXYDMCompletedEventHandler(object sender, GetInfoByTYSHXYDMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoByTYSHXYDMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoByTYSHXYDMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void queryBytyshxydmCompletedEventHandler(object sender, queryBytyshxydmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryBytyshxydmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryBytyshxydmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetNameZzjgdmByFuzzySearchCompletedEventHandler(object sender, GetNameZzjgdmByFuzzySearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNameZzjgdmByFuzzySearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNameZzjgdmByFuzzySearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
