//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.8.3928.0。
// 
namespace PullData.ConvergenceService.PersonInfo
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IDInfoSoap", Namespace="http://tempuri.org/")]
    public partial class IDInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback matchOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifyBysfzhmOperationCompleted;
        
        /// <remarks/>
        public IDInfo() {
            this.Url = "http://220.160.52.50:801/ConvergenceSerivce/IDInfo.asmx";
        }
        
        /// <remarks/>
        public event matchCompletedEventHandler matchCompleted;
        
        /// <remarks/>
        public event queryByIDCompletedEventHandler queryByIDCompleted;
        
        /// <remarks/>
        public event verifyBysfzhmCompletedEventHandler verifyBysfzhmCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/match", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string match(string guid, string id, string name) {
            object[] results = this.Invoke("match", new object[] {
                        guid,
                        id,
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginmatch(string guid, string id, string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("match", new object[] {
                        guid,
                        id,
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endmatch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void matchAsync(string guid, string id, string name) {
            this.matchAsync(guid, id, name, null);
        }
        
        /// <remarks/>
        public void matchAsync(string guid, string id, string name, object userState) {
            if ((this.matchOperationCompleted == null)) {
                this.matchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmatchOperationCompleted);
            }
            this.InvokeAsync("match", new object[] {
                        guid,
                        id,
                        name}, this.matchOperationCompleted, userState);
        }
        
        private void OnmatchOperationCompleted(object arg) {
            if ((this.matchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.matchCompleted(this, new matchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryByID(string guid, string id) {
            object[] results = this.Invoke("queryByID", new object[] {
                        guid,
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryByID(string guid, string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryByID", new object[] {
                        guid,
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryByIDAsync(string guid, string id) {
            this.queryByIDAsync(guid, id, null);
        }
        
        /// <remarks/>
        public void queryByIDAsync(string guid, string id, object userState) {
            if ((this.queryByIDOperationCompleted == null)) {
                this.queryByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryByIDOperationCompleted);
            }
            this.InvokeAsync("queryByID", new object[] {
                        guid,
                        id}, this.queryByIDOperationCompleted, userState);
        }
        
        private void OnqueryByIDOperationCompleted(object arg) {
            if ((this.queryByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryByIDCompleted(this, new queryByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verifyBysfzhm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string verifyBysfzhm(string guid, string sfzhm, string xm) {
            object[] results = this.Invoke("verifyBysfzhm", new object[] {
                        guid,
                        sfzhm,
                        xm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginverifyBysfzhm(string guid, string sfzhm, string xm, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("verifyBysfzhm", new object[] {
                        guid,
                        sfzhm,
                        xm}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndverifyBysfzhm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verifyBysfzhmAsync(string guid, string sfzhm, string xm) {
            this.verifyBysfzhmAsync(guid, sfzhm, xm, null);
        }
        
        /// <remarks/>
        public void verifyBysfzhmAsync(string guid, string sfzhm, string xm, object userState) {
            if ((this.verifyBysfzhmOperationCompleted == null)) {
                this.verifyBysfzhmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyBysfzhmOperationCompleted);
            }
            this.InvokeAsync("verifyBysfzhm", new object[] {
                        guid,
                        sfzhm,
                        xm}, this.verifyBysfzhmOperationCompleted, userState);
        }
        
        private void OnverifyBysfzhmOperationCompleted(object arg) {
            if ((this.verifyBysfzhmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyBysfzhmCompleted(this, new verifyBysfzhmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void matchCompletedEventHandler(object sender, matchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class matchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal matchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void queryByIDCompletedEventHandler(object sender, queryByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void verifyBysfzhmCompletedEventHandler(object sender, verifyBysfzhmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyBysfzhmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifyBysfzhmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
